import os

OUTPUTS_PATH = os.path.join("outputs")
GLOBAL_VECTORSTORE_PATH = os.path.join(OUTPUTS_PATH, "vectorstore")
UPLOADS_PATH = os.path.join("uploads")
JOBS_PATH = os.path.join("jobs")
OCR_ENABLED_DEFAULT = False
OCR_LANGUAGES = ["de", "en"]
OCR_MIN_CONFIDENCE = 0.5
OCR_MAX_TEXT_LENGTH = 2000
FACES_ENABLED_DEFAULT = True
FACES_MIN_CONFIDENCE = 0.6
FACES_MAX_PER_SCENE = 10
PERSONS_CLUSTERING_ENABLED = False
PERSONS_CLUSTERING_METHOD = "dbscan"
PERSONS_DBSCAN_EPS = 0.3
PERSONS_DBSCAN_MIN_SAMPLES = 2
PERSONS_UPDATE_SCENES = False
